-- local header = {
--   [[ ⣇⣿⠘⣿⣿⣿⡿⡿⣟⣟⢟⢟⢝⠵⡝⣿⡿⢂⣼⣿⣷⣌⠩⡫⡻⣝⠹⢿⣿⣷ ]],
--   [[ ⡆⣿⣆⠱⣝⡵⣝⢅⠙⣿⢕⢕⢕⢕⢝⣥⢒⠅⣿⣿⣿⡿⣳⣌⠪⡪⣡⢑⢝⣇ ]],
--   [[ ⡆⣿⣿⣦⠹⣳⣳⣕⢅⠈⢗⢕⢕⢕⢕⢕⢈⢆⠟⠋⠉⠁⠉⠉⠁⠈⠼⢐⢕⢽ ]],
--   [[ ⡗⢰⣶⣶⣦⣝⢝⢕⢕⠅⡆⢕⢕⢕⢕⢕⣴⠏⣠⡶⠛⡉⡉⡛⢶⣦⡀⠐⣕⢕ ]],
--   [[ ⡝⡄⢻⢟⣿⣿⣷⣕⣕⣅⣿⣔⣕⣵⣵⣿⣿⢠⣿⢠⣮⡈⣌⠨⠅⠹⣷⡀⢱⢕ ]],
--   [[ ⡝⡵⠟⠈⢀⣀⣀⡀⠉⢿⣿⣿⣿⣿⣿⣿⣿⣼⣿⢈⡋⠴⢿⡟⣡⡇⣿⡇⡀⢕ ]],
--   [[ ⡝⠁⣠⣾⠟⡉⡉⡉⠻⣦⣻⣿⣿⣿⣿⣿⣿⣿⣿⣧⠸⣿⣦⣥⣿⡇⡿⣰⢗⢄ ]],
--   [[ ⠁⢰⣿⡏⣴⣌⠈⣌⠡⠈⢻⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣬⣉⣉⣁⣄⢖⢕⢕⢕ ]],
--   [[ ⡀⢻⣿⡇⢙⠁⠴⢿⡟⣡⡆⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣵⣵⣿ ]],
--   [[ ⡻⣄⣻⣿⣌⠘⢿⣷⣥⣿⠇⣿⣿⣿⣿⣿⣿⠛⠻⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿ ]],
--   [[ ⣷⢄⠻⣿⣟⠿⠦⠍⠉⣡⣾⣿⣿⣿⣿⣿⣿⢸⣿⣦⠙⣿⣿⣿⣿⣿⣿⣿⣿⠟ ]],
--   [[ ⡕⡑⣑⣈⣻⢗⢟⢞⢝⣻⣿⣿⣿⣿⣿⣿⣿⠸⣿⠿⠃⣿⣿⣿⣿⣿⣿⡿⠁⣠ ]],
--   [[ ⡝⡵⡈⢟⢕⢕⢕⢕⣵⣿⣿⣿⣿⣿⣿⣿⣿⣿⣶⣶⣿⣿⣿⣿⣿⠿⠋⣀⣈⠙ ]],
--   [[ ⡝⡵⡕⡀⠑⠳⠿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠿⠛⢉⡠⡲⡫⡪⡪⡣ ]],
-- }
local header = {
[[                  _            ____                          ]],
[[                 : \           |   \    .                    ]],
[[                 |  \ .        |    :   |\            /\     ]],
[[              .  |   :|\__     |    |   | \          /  \    ]],
[[              |\ |   |! \ \    |    |   | |\        /   /    ]],
[[ \"-.______   | \:   ||\ \ \   |    |   | | \      /   /     ]],
[[  \_       "-_|  |\  || \ \/   |    |___| ! |\____/  _/-. /\ ]],
[[    "-_   ____:  |_\ ||  \/  ___\  __  _//  | |  ___ \---" / ]],
[[       \  \   |  _____,  /___\___\/ / /   \_! |  // _/  / /  ]],
[[     ___\_ \__|  |    | __. _/____ / /     /  > // /    \/   ]],
[[   //_________|  /    |/  |/  \__// /     /  /_/ \/          ]],
[[              | /     |   :      | /     /__/                ]],
[[              |/                 |/                          ]],
}
local settings = {
  options = {
    mapping_keys = true,
    cursor_column = 0.5,
    empty_lines_between_mappings = true,
    disable_statuslines = false,
    paddings = { 1, 1, 1, 1 },
  },
  header = {
    type = "text",
    align = "center",
    fold_section = false,
    title = "Header",
    margin = 2,
    content = header,
    highlight = "Statement",
    default_color = "",
    oldfiles_amount = 0,
  },
  header_2 = {
    type = "text",
    oldfiles_directory = false,
    align = "center",
    fold_section = false,
    title = "Quote",
    margin = 10,
    content = require("startup.functions").quote(),
    highlight = "Constant",
    default_color = "",
    oldfiles_amount = 0,
  },
  body = {
    type = "mapping",
    align = "center",
    fold_section = false,
    title = "Basic Commands",
    margin = 2,
    content = {
      { "📁 Find File", "Telescope find_files", "<leader>ff" },
      { "💻 Old Files", "Telescope oldfiles", "<leader>of" },
      { "💬 Find Word", "Telescope live_grep", "<leader>lg" },
      { "🔭 File Browser", "Telescope file_browser", "<leader>fb" },
      { "🎨 Colorschemes", "Telescope colorscheme", "<leader>cs" },
      { "🆕 New File", "lua require'startup'.new_file()", "<leader>nf" },
    },
    highlight = "String",
    default_color = "",
    oldfiles_amount = 0,
  },
  clock = {
    type = "text",
    content = function()
      local clock = " " .. os.date("%H:%M")
      local date = " " .. os.date("%d-%m-%y")
      return { clock, date }
    end,
    oldfiles_directory = false,
    align = "center",
    fold_section = false,
    title = "",
    margin = 2,
    highlight = "TSString",
    default_color = "#FFFFFF",
    oldfiles_amount = 10,
  },
  colors = {
    background = "#1f2227",
    folded_section = "#56b6c2",
  },
  parts = {
    "header",
    "header_2",
    "body",
    "clock",
  },
}
return settings
